{
	"forgotPasswordLink": "Forgot Your Password?",
	"jcr:description": "Best comp ever",
	"password": "Password",
	"jcr:title": "Best comp ever",
	"modifyProjectFormHeader": "Make changes to the project below",
	"deleteSentenceFragmentTwo": "permanently?",
	"jcr:created": "Thu Mar 19 2015 10:46:10 GMT-0400",
	"homeLink": "Home",
	"createProjectTitle": "Create a New Project",
	"deleteSentenceFragmentOne": "Are you sure you would like to delete",
	"openDate": "Open Date",
	"jcr:createdBy": "admin",
	"newTaskFormHeader": "Fill in details for the task",
	"backLink": "Go Back",
	"activeTasksHeader": "Active Tasks",
	"appSupportLink": "App Support",
	"username": "Username",
	"deleteProjectTitle": "Delete Project?",
	"calendarLink": "Calendar",
	"sortBy": "Sort By",
	"modifyTaskFormHeader": "Make changes to the task below",
	"status": "Status",
	"newProjectFormHeader": "Fill in details for the project",
	"jcr:primaryType": "cq:Component",
	"loginFormTitle": "User Login",
	"activeProjectsHeader": "Active Projects",
	"project": "Project",
	"taskName": "Task Name",
	"settingsLink": "Settings",
	"delete": "Delete",
	"edit": "Edit",
	"deleteSentenceFragmentThree": "Once deleted, you will no longer be able to access it again.",
	"searchLink": "Search",
	"buttons": {
		"submitProject": "Submit New Project",
		"confirmChanges": "Confirm Changes",
		"addTaskButton": "New Task",
		"submitComment": "Submit Comment",
		"deleteTask": "Delete Task",
		"jcr:primaryType": "nt:unstructured",
		"importTaskButton": "Import Task",
		"addNewProject": "Add New Project",
		"deleteProject": "Delete Project",
		"loginButton": "Login",
		"cancelButton": "Cancel",
		"submitTask": "Submit New Task",
		"deleteButton": "Delete"
	},
	"fields": {
		"projectDescription": "Project Description",
		"taskTitle": "Task Title",
		"projectSummary": "Project Summary",
		"projectType": "Project Type",
		"creationDate": "Creation Date",
		"jcr:primaryType": "nt:unstructured",
		"openedBy": "Opened By",
		"projectTitle": "Project Title"
	},
	"projectTypes": {
		"documentation": "Documentation",
		"task": "Task",
		"cr": "Change Request",
		"tr": "Trouble Request",
		"bug": "Bug",
		"training": "Training",
		"jcr:primaryType": "nt:unstructured"
	},
	"taskPriorities": {
		"blocker": "Blocker",
		"major": "Major",
		"critical": "Critical",
		"minor": "Minor",
		"jcr:primaryType": "nt:unstructured"
	},
	"taskStatus": {
		"approved": "Approved",
		"development": "Development",
		"reopened": "Reopened",
		"testing": "Testing",
		"open": "Open",
		"qcr": "Code Review",
		"jcr:primaryType": "nt:unstructured"
	}
}
